# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Cloudtips-SDK-iOS-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Cloudtips', :path => "../sdk"
#  pod 'Cloudtips', :git => "https://github.com/cloudpayments/CloudTips-SDK-iOS", :branch => "master"

  pod 'Cloudpayments', :git => "https://github.com/cloudpayments/CloudPayments-SDK-iOS", :branch => "master"
  pod 'CloudpaymentsNetworking', :git => "https://github.com/cloudpayments/CloudPayments-SDK-iOS", :branch => "master"

end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end

